services:
  db:
    env_file:
      - .env
    image: postgres:17-alpine3.20
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:${DB_PORT}

  base_backend_app:
    env_file:
      - .env
    build: 
      dockerfile: .docker/Dockerfile
      context: ../
      args:
        - APP_PORT=${APP_PORT}
        - POETRY_VERSION=${POETRY_VERSION}
    command: python /app/manage.py runserver 0.0.0.0:${APP_PORT}
    volumes:
      - ../:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db

volumes:
  postgres_data: